name: Project specific tests
description: Run project specific tests
runs:
  using: composite
  steps:
      - name: Run autograding
        uses: education/autograding@v1

      - run: |
          echo Running count.py
          diff <(cat <<EOF
          a: 1
          b: 1
          f: 1
          o: 2
          r: 1
          EOF) <(echo foobar | python3 src/counts.py)
        shell: bash

      - run: |
          echo Running password "foobar"
          [ `echo False` == `python3 src/password.py foobar` ]
        shell: bash
        
      - run: |
          echo Running password "Foob@r1"
          [ `echo True` == `python3 src/password.py Foob@r1` ]
        shell: bash

      - run: |
          echo Running hex encoding of "foobar"
          [ `echo 0x660x6f0x6f0x620x610x72` == `python3 src/hex.py encode foobar` ]
        shell: bash
        
      - run: |
          echo Running hex decoding of "0x660x6f0x6f0x620x610x72"
          [ `echo foobar` == `python3 src/hex.py decode 0x660x6f0x6f0x620x610x72` ]
        shell: bash
  